spring.application.name=exam-final-prog4

spring.datasource.url=jdbc:postgresql://ep-cold-credit-axa5kwbb-pooler.c-4.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_iMQkzc8umGC5&sslmode=require&channelBinding=require
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

aws.s3.bucket=${AWS_S3_BUCKET:}
aws.eventBridge.bus=${AWS_EVENTBRIDGE_BUS:}
