spring.application.name=exam-final-prog4

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true

aws.s3.bucket=${AWS_S3_BUCKET:}
aws.eventBridge.bus=${AWS_EVENTBRIDGE_BUS:}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000
